/**
 * Icons.tsx — Centralized Icon System
 *
 * Purpose: Single source of truth for all icons used in the application.
 * Uses lucide-react for consistent SVG icons with accessibility labels.
 *
 * Usage: Import named icons from this module instead of using emoji or
 * inline SVG. All icons have aria-hidden="true" and accessible labels
 * via the `title` prop.
 *
 * Example:
 *   import { FileText, X } from "./Icons";
 *   <FileText size={16} />
 *   <X title="Close" />
 */

import {
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bold,
  BringToFront,
  Brush,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Copy,
  Crop,
  Delete,
  Download,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileImage,
  FileText,
  Filter,
  FlipHorizontal,
  FlipVertical,
  FolderOpen,
  GripVertical,
  Hand,
  Highlighter,
  Image,
  ImagePlus,
  Italic,
  Layers,
  Lock,
  Maximize2,
  Menu,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Move,
  MousePointer2,
  PaintBucket,
  Pen,
  Pencil,
  Plus,
  Redo2,
  RotateCcw,
  RotateCw,
  Save,
  Search,
  SendToBack,
  Settings,
  Sidebar,
  SlidersHorizontal,
  Square,
  Stamp,
  Sun,
  Text,
  Trash2,
  Type,
  Underline,
  Undo2,
  Unlock,
  Upload,
  X,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

// ── Re-export all used icons ────────────────────────────────────────
export {
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bold,
  BringToFront,
  Brush,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Copy,
  Crop,
  Delete,
  Download,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileImage,
  FileText,
  Filter,
  FlipHorizontal,
  FlipVertical,
  FolderOpen,
  GripVertical,
  Hand,
  Highlighter,
  Image,
  ImagePlus,
  Italic,
  Layers,
  Lock,
  Maximize2,
  Menu,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Move,
  MousePointer2,
  PaintBucket,
  Pen,
  Pencil,
  Plus,
  Redo2,
  RotateCcw,
  RotateCw,
  Save,
  Search,
  SendToBack,
  Settings,
  Sidebar,
  SlidersHorizontal,
  Square,
  Stamp,
  Sun,
  Text,
  Trash2,
  Type,
  Underline,
  Undo2,
  Unlock,
  Upload,
  X,
  ZoomIn,
  ZoomOut,
};

// ── Tool icons map ─────────────────────────────────────────────────
// Maps tool types to their corresponding icon components
// oxlint-disable-next-line react/only-export-components
export const TOOL_ICONS: Record<string, React.ComponentType<{ size?: number; className?: string }>> = {
  select: MousePointer2,
  hand: Hand,
  text: Type,
  image: Image,
  shape: Square,
  draw: Pencil,
  highlight: Highlighter,
  signature: Pen,
  stamp: Stamp,
  erase: Eraser,
};
